/**
 * Cyberdeck 2025 - Base Theme Template
 * All language support and scopes preserved
 * Colors are referenced from the palette parameter
 */

// Helper to add alpha to hex color
const alpha = (hex, a) => {
  const alphaHex = Math.round(a * 255).toString(16).padStart(2, '0');
  return `${hex}${alphaHex}`;
};

module.exports = function buildTheme(palette) {
  return {
    name: palette.name,
    $schema: "vscode://schemas/color-theme",

    semanticHighlighting: true,

    // ========================================================================
    // WORKBENCH COLORS (UI Elements)
    // ========================================================================
    colors: {
      // ----------------------------------------------------------------------
      // BASE COLORS
      // ----------------------------------------------------------------------
      "descriptionForeground": palette.fg.dimmed,
      "editorWidget.foreground": palette.syntax.builtin,
      "errorForeground": palette.accent.primary,
      "focusBorder": palette.bg.base,
      "foreground": palette.fg.dimmed,
      "icon.foreground": palette.accent.primary,
      "sash.hoverBorder": palette.accent.primary,
      "selection.background": palette.accent.hotPink,
      "widget.border": palette.bg.elevated,
      "widget.shadow": palette.bg.elevated,

      // ----------------------------------------------------------------------
      // CONTRAST COLORS
      // ----------------------------------------------------------------------
      "contrastActiveBorder": palette.accent.primary,
      "contrastBorder": palette.bg.elevated,

      // ----------------------------------------------------------------------
      // ACTIVITY BAR
      // ----------------------------------------------------------------------
      "activityBar.activeBackground": alpha(palette.accent.primary, 0.2),
      "activityBar.activeBorder": palette.accent.primary,
      "activityBar.background": palette.bg.base,
      "activityBar.border": palette.bg.elevated,
      "activityBar.foreground": palette.accent.pink,
      "activityBar.inactiveForeground": palette.accent.primary,
      "activityBarBadge.background": palette.accent.pink,
      "activityBarBadge.foreground": palette.bg.darker,

      // ----------------------------------------------------------------------
      // BADGE
      // ----------------------------------------------------------------------
      "badge.background": palette.accent.primary,
      "badge.foreground": palette.bg.darker,

      // ----------------------------------------------------------------------
      // BREADCRUMBS
      // ----------------------------------------------------------------------
      "breadcrumb.activeSelectionForeground": palette.fg.bright,
      "breadcrumb.background": palette.bg.base,
      "breadcrumb.focusForeground": palette.accent.primary,
      "breadcrumb.foreground": alpha(palette.fg.bright, 0.6),
      "breadcrumbPicker.background": palette.bg.base,

      // ----------------------------------------------------------------------
      // BUTTON CONTROLS
      // ----------------------------------------------------------------------
      "button.background": alpha(palette.accent.primary, 0.13),
      "button.foreground": palette.fg.bright,
      "button.hoverBackground": palette.fg.dimmed,

      // ----------------------------------------------------------------------
      // DEBUG
      // ----------------------------------------------------------------------
      "debugExceptionWidget.background": palette.bg.base,
      "debugExceptionWidget.border": palette.fg.bright,
      "debugToolBar.background": palette.bg.debug,

      // ----------------------------------------------------------------------
      // DIFF EDITOR
      // ----------------------------------------------------------------------
      "diffEditor.insertedTextBackground": alpha(palette.state.hint, 0.15),
      "diffEditor.removedTextBackground": alpha(palette.accent.primary, 0.09),

      // ----------------------------------------------------------------------
      // DROPDOWN CONTROLS
      // ----------------------------------------------------------------------
      "dropdown.background": palette.bg.base,
      "dropdown.border": palette.bg.base,
      "dropdown.foreground": palette.fg.dimmed,

      // ----------------------------------------------------------------------
      // EDITOR
      // ----------------------------------------------------------------------
      "editor.background": palette.bg.base,
      "editor.findMatchBackground": palette.bg.highlight,
      "editor.findMatchHighlightBackground": alpha(palette.bg.highlight, 0.53),
      "editor.findRangeHighlightBackground": alpha(palette.bg.highlight, 0.1),
      "editor.foreground": palette.fg.base,
      "editor.hoverHighlightBackground": alpha(palette.bg.highlight, 0.3),
      "editor.inactiveSelectionBackground": alpha(palette.fg.bright, 0.2),
      "editor.lineHighlightBackground": alpha(palette.bg.highlight, 0.4),
      "editor.lineHighlightBorder": alpha(palette.bg.highlight, 0.4),
      "editor.rangeHighlightBackground": alpha(palette.fg.dimmed, 0.22),
      "editor.selectionBackground": alpha(palette.bg.selection, 0.53),
      "editor.selectionHighlightBackground": alpha(palette.accent.primary, 0.2),
      "editor.snippetFinalTabstopHighlightBackground": palette.bg.darker,
      "editor.snippetFinalTabstopHighlightBorder": palette.bg.darker,
      "editor.snippetTabstopHighlightBackground": palette.bg.darker,
      "editor.snippetTabstopHighlightBorder": palette.bg.darker,
      "editor.wordHighlightBackground": alpha(palette.bg.highlight, 0.53),
      "editor.wordHighlightStrongBackground": alpha(palette.bg.highlight, 0.53),
      "editorBracketMatch.background": alpha(palette.bg.highlight, 0.4),
      "editorBracketMatch.border": palette.accent.pink,
      "editorCodeLens.foreground": alpha(palette.fg.bright, 0.8),
      "editorCursor.foreground": palette.special.cursor,
      "editorError.border": palette.bg.base,
      "editorError.foreground": palette.accent.primary,
      "editorGroup.border": palette.bg.elevated,
      "editorGroup.dropBackground": alpha(palette.fg.dimmed, 0.2),
      "editorGroup.emptyBackground": alpha(palette.fg.dimmed, 0.2),
      "editorGroupHeader.noTabsBackground": palette.bg.base,
      "editorGroupHeader.tabsBackground": palette.bg.base,
      "editorGroupHeader.tabsBorder": palette.bg.darker,
      "editorGutter.addedBackground": alpha(palette.state.added, 0.84),
      "editorGutter.background": palette.bg.base,
      "editorGutter.deletedBackground": alpha(palette.state.deleted, 0.64),
      "editorGutter.modifiedBackground": palette.state.modified,
      "editorHint.border": alpha(palette.state.hint, 0),
      "editorHint.foreground": palette.state.hint,
      "editorHoverWidget.background": palette.bg.darker,
      "editorHoverWidget.border": palette.bg.elevated,
      "editorIndentGuide.activeBackground1": palette.bg.elevated,
      "editorIndentGuide.background1": alpha(palette.fg.dimmed, 0.22),
      "editorInfo.border": palette.bg.base,
      "editorInfo.foreground": palette.accent.primary,
      "editorLineNumber.activeForeground": palette.fg.dimmed,
      "editorLineNumber.foreground": palette.fg.dimmed,
      "editorLink.activeForeground": palette.special.link,
      "editorMarkerNavigation.background": alpha("#434356", 0.16),
      "editorMarkerNavigationError.background": palette.accent.primary,
      "editorMarkerNavigationWarning.background": palette.state.warning,
      "editorOverviewRuler.addedForeground": alpha("#09f7a0", 0.6),
      "editorOverviewRuler.border": palette.bg.base,
      "editorOverviewRuler.commonContentForeground": alpha(palette.state.warning, 0.27),
      "editorOverviewRuler.currentContentForeground": alpha(palette.bg.elevated, 0.27),
      "editorOverviewRuler.deletedForeground": alpha(palette.accent.primary, 0.6),
      "editorOverviewRuler.errorForeground": alpha(palette.state.errorBg, 0.93),
      "editorOverviewRuler.findMatchForeground": alpha(palette.bg.highlight, 0.53),
      "editorOverviewRuler.incomingContentForeground": alpha("#cac4f5", 0.27),
      "editorOverviewRuler.modifiedForeground": alpha(palette.fg.dimmed, 0.6),
      "editorOverviewRuler.warningForeground": alpha(palette.accent.primary, 0.8),
      "editorRuler.foreground": alpha(palette.bg.highlight, 0.2),
      "editorSuggestWidget.background": palette.bg.darker,
      "editorSuggestWidget.border": palette.bg.elevated,
      "editorSuggestWidget.foreground": palette.fg.soft,
      "editorSuggestWidget.highlightForeground": palette.accent.primary,
      "editorSuggestWidget.selectedBackground": palette.bg.highlight,
      "editorWarning.border": palette.bg.base,
      "editorWarning.foreground": palette.state.warning,
      "editorWhitespace.foreground": alpha(palette.fg.bright, 0.13),
      "editorWidget.background": palette.bg.base,
      "editorWidget.border": palette.bg.elevated,

      // ----------------------------------------------------------------------
      // EXTENSION BUTTON
      // ----------------------------------------------------------------------
      "extensionButton.prominentBackground": palette.accent.primary,
      "extensionButton.prominentForeground": palette.bg.darker,
      "extensionButton.prominentHoverBackground": palette.syntax.type,

      // ----------------------------------------------------------------------
      // GIT DECORATIONS
      // ----------------------------------------------------------------------
      "gitDecoration.addedResourceForeground": alpha(palette.accent.primary, 0.8),
      "gitDecoration.conflictingResourceForeground": palette.state.warning,
      "gitDecoration.deletedResourceForeground": alpha(palette.state.errorBg, 0.93),
      "gitDecoration.ignoredResourceForeground": alpha(palette.fg.bright, 0.35),
      "gitDecoration.modifiedResourceForeground": palette.accent.primary,
      "gitDecoration.untrackedResourceForeground": palette.fg.soft,

      // ----------------------------------------------------------------------
      // INPUT CONTROLS
      // ----------------------------------------------------------------------
      "input.background": palette.bg.darker,
      "input.border": palette.bg.darker,
      "input.foreground": palette.fg.muted,
      "input.placeholderForeground": palette.fg.muted,
      "inputOption.activeBorder": palette.fg.muted,
      "inputValidation.errorBackground": alpha(palette.accent.primary, 0.5),
      "inputValidation.errorBorder": alpha(palette.accent.primary, 0),
      "inputValidation.errorForeground": palette.accent.primary,
      "inputValidation.infoBackground": palette.bg.base,
      "inputValidation.infoBorder": palette.syntax.type,
      "inputValidation.infoForeground": palette.accent.primary,
      "inputValidation.warningBackground": palette.bg.base,
      "inputValidation.warningBorder": palette.state.warning,
      "inputValidation.warningForeground": palette.state.warning,

      // ----------------------------------------------------------------------
      // LISTS AND TREES
      // ----------------------------------------------------------------------
      "list.activeSelectionBackground": alpha(palette.bg.elevated, 0.5),
      "list.activeSelectionForeground": palette.accent.hotPink,
      "list.dropBackground": alpha(palette.bg.highlight, 0.4),
      "list.errorForeground": alpha(palette.accent.primary, 0.9),
      "list.focusBackground": palette.bg.base,
      "list.focusForeground": palette.fg.bright,
      "list.highlightForeground": palette.accent.primary,
      "list.hoverBackground": palette.bg.hover,
      "list.hoverForeground": palette.accent.hotPink,
      "list.inactiveFocusBackground": palette.bg.base,
      "list.inactiveSelectionBackground": alpha(palette.bg.highlight, 0.4),
      "list.inactiveSelectionForeground": palette.fg.bright,
      "list.warningForeground": palette.state.warning,
      "listFilterWidget.background": palette.bg.darker,
      "listFilterWidget.noMatchesOutline": palette.accent.primary,
      "listFilterWidget.outline": palette.state.hint,

      // ----------------------------------------------------------------------
      // MENU
      // ----------------------------------------------------------------------
      "menu.background": palette.bg.base,
      "menu.foreground": palette.accent.primary,
      "menu.selectionBackground": alpha(palette.accent.primary, 0.5),
      "menu.selectionBorder": palette.bg.base,
      "menu.selectionForeground": palette.accent.primary,
      "menu.separatorBackground": palette.accent.primary,
      "menubar.selectionBackground": palette.bg.base,
      "menubar.selectionBorder": palette.bg.base,
      "menubar.selectionForeground": palette.accent.primary,

      // ----------------------------------------------------------------------
      // MERGE CONFLICTS
      // ----------------------------------------------------------------------
      "merge.border": alpha(palette.bg.base, 0),
      "merge.commonContentBackground": alpha(palette.state.warning, 0.13),
      "merge.commonHeaderBackground": alpha(palette.state.warning, 0.27),
      "merge.currentContentBackground": alpha(palette.bg.elevated, 0.13),
      "merge.currentHeaderBackground": alpha(palette.bg.elevated, 0.27),
      "merge.incomingContentBackground": alpha("#aea8dc", 0.13),
      "merge.incomingHeaderBackground": alpha("#aea8dc", 0.27),

      // ----------------------------------------------------------------------
      // MINIMAP
      // ----------------------------------------------------------------------
      "minimap.errorHighlight": alpha(palette.state.errorBg, 0.93),
      "minimap.findMatchHighlight": alpha(palette.accent.primary, 0.93),
      "minimap.warningHighlight": alpha(palette.state.warning, 0.93),
      "minimapGutter.addedBackground": palette.syntax.type,
      "minimapGutter.deletedBackground": palette.accent.primary,
      "minimapGutter.modifiedBackground": palette.state.hint,

      // ----------------------------------------------------------------------
      // NOTIFICATIONS
      // ----------------------------------------------------------------------
      "notificationCenter.border": palette.bg.base,
      "notificationCenterHeader.background": palette.bg.base,
      "notificationCenterHeader.foreground": palette.fg.muted,
      "notificationLink.foreground": palette.fg.bright,
      "notificationToast.border": palette.bg.base,
      "notifications.background": palette.bg.base,
      "notifications.border": palette.bg.base,
      "notifications.foreground": palette.fg.muted,

      // ----------------------------------------------------------------------
      // PANEL
      // ----------------------------------------------------------------------
      "panel.background": palette.bg.base,
      "panel.border": palette.accent.hotPink,
      "panelTitle.activeBorder": palette.accent.hotPink,
      "panelTitle.activeForeground": palette.accent.hotPink,
      "panelTitle.inactiveForeground": palette.fg.inactive,

      // ----------------------------------------------------------------------
      // PEEK VIEW
      // ----------------------------------------------------------------------
      "peekView.border": palette.fg.dimmed,
      "peekViewEditor.background": palette.bg.base,
      "peekViewEditor.matchHighlightBackground": palette.bg.highlight,
      "peekViewEditor.matchHighlightBorder": palette.bg.base,
      "peekViewEditorGutter.background": palette.bg.base,
      "peekViewResult.background": palette.bg.base,
      "peekViewResult.fileForeground": palette.state.warning,
      "peekViewResult.lineForeground": palette.fg.bright,
      "peekViewResult.matchHighlightBackground": palette.bg.base,
      "peekViewResult.selectionBackground": "#0d181a",
      "peekViewResult.selectionForeground": palette.fg.bright,
      "peekViewTitle.background": palette.bg.base,
      "peekViewTitleDescription.foreground": palette.fg.bright,
      "peekViewTitleLabel.foreground": palette.accent.primary,

      // ----------------------------------------------------------------------
      // PICKER GROUP
      // ----------------------------------------------------------------------
      "pickerGroup.border": palette.syntax.type,
      "pickerGroup.foreground": palette.fg.muted,

      // ----------------------------------------------------------------------
      // PROGRESS BAR
      // ----------------------------------------------------------------------
      "progressBar.background": palette.accent.primary,

      // ----------------------------------------------------------------------
      // SCROLLBAR
      // ----------------------------------------------------------------------
      "scrollbar.shadow": palette.bg.elevated,
      "scrollbarSlider.activeBackground": alpha(palette.bg.highlight, 0.47),
      "scrollbarSlider.background": alpha(palette.bg.highlight, 0.2),
      "scrollbarSlider.hoverBackground": alpha(palette.bg.highlight, 0.33),

      // ----------------------------------------------------------------------
      // SETTINGS EDITOR
      // ----------------------------------------------------------------------
      "settings.checkboxBackground": palette.bg.base,
      "settings.checkboxBorder": palette.bg.base,
      "settings.checkboxForeground": palette.fg.dimmed,
      "settings.dropdownBackground": palette.bg.base,
      "settings.dropdownBorder": palette.bg.base,
      "settings.dropdownForeground": palette.fg.dimmed,
      "settings.dropdownListBorder": palette.bg.highlight,
      "settings.headerForeground": palette.accent.primary,
      "settings.modifiedItemIndicator": palette.syntax.type,
      "settings.numberInputBackground": palette.bg.darker,
      "settings.numberInputBorder": palette.bg.darker,
      "settings.numberInputForeground": palette.fg.muted,
      "settings.textInputBackground": palette.bg.base,
      "settings.textInputBorder": palette.bg.base,
      "settings.textInputForeground": palette.fg.dimmed,

      // ----------------------------------------------------------------------
      // SIDE BAR
      // ----------------------------------------------------------------------
      "sideBar.background": palette.bg.darker,
      "sideBar.border": palette.bg.elevated,
      "sideBar.dropBackground": palette.bg.darker,
      "sideBar.foreground": palette.fg.muted,
      "sideBarSectionHeader.background": palette.bg.base,
      "sideBarSectionHeader.border": palette.bg.elevated,
      "sideBarSectionHeader.foreground": palette.accent.secondary,
      "sideBarTitle.foreground": palette.accent.secondary,

      // ----------------------------------------------------------------------
      // STATUS BAR
      // ----------------------------------------------------------------------
      "statusBar.background": palette.bg.base,
      "statusBar.border": palette.bg.elevated,
      "statusBar.debuggingBackground": palette.bg.base,
      "statusBar.debuggingBorder": alpha("#08080f", 0.69),
      "statusBar.debuggingForeground": palette.syntax.builtin,
      "statusBar.foreground": palette.accent.hotPink,
      "statusBar.noFolderBackground": palette.bg.base,
      "statusBar.noFolderBorder": palette.bg.base,
      "statusBar.noFolderForeground": palette.fg.bright,
      "statusBarItem.activeBackground": alpha(palette.bg.base, 0.4),
      "statusBarItem.hoverBackground": palette.bg.elevated,
      "statusBarItem.prominentBackground": palette.bg.elevated,
      "statusBarItem.prominentHoverBackground": palette.bg.highlight,

      // ----------------------------------------------------------------------
      // TABS
      // ----------------------------------------------------------------------
      "tab.activeBackground": palette.bg.base,
      "tab.activeBorder": palette.accent.hotPink,
      "tab.activeBorderTop": palette.bg.base,
      "tab.activeForeground": palette.accent.hotPink,
      "tab.activeModifiedBorder": palette.state.hint,
      "tab.border": palette.bg.elevated,
      "tab.inactiveBackground": palette.bg.base,
      "tab.inactiveForeground": palette.fg.inactive,
      "tab.unfocusedActiveBackground": palette.bg.inactive,
      "tab.unfocusedActiveBorder": palette.bg.base,
      "tab.unfocusedActiveForeground": palette.accent.secondary,
      "tab.unfocusedHoverBackground": alpha(palette.accent.primary, 0.13),
      "tab.unfocusedInactiveForeground": palette.fg.inactive,

      // ----------------------------------------------------------------------
      // TERMINAL
      // ----------------------------------------------------------------------
      "terminal.ansiBlack": palette.terminal.black,
      "terminal.ansiBlue": palette.terminal.blue,
      "terminal.ansiBrightBlack": palette.terminal.brightBlack,
      "terminal.ansiBrightBlue": palette.terminal.brightBlue,
      "terminal.ansiBrightCyan": palette.terminal.brightCyan,
      "terminal.ansiBrightGreen": palette.terminal.brightGreen,
      "terminal.ansiBrightMagenta": palette.terminal.brightMagenta,
      "terminal.ansiBrightRed": palette.terminal.brightRed,
      "terminal.ansiBrightWhite": palette.terminal.brightWhite,
      "terminal.ansiBrightYellow": palette.terminal.brightYellow,
      "terminal.ansiCyan": palette.terminal.cyan,
      "terminal.ansiGreen": palette.terminal.green,
      "terminal.ansiMagenta": palette.terminal.magenta,
      "terminal.ansiRed": palette.terminal.red,
      "terminal.ansiWhite": palette.terminal.white,
      "terminal.ansiYellow": palette.terminal.yellow,
      "terminal.background": palette.bg.darker,
      "terminalCursor.background": palette.bg.darker,
      "terminalCursor.foreground": palette.accent.primary,

      // ----------------------------------------------------------------------
      // TEXT COLORS
      // ----------------------------------------------------------------------
      "textBlockQuote.background": palette.bg.base,
      "textBlockQuote.border": palette.fg.muted,
      "textCodeBlock.background": palette.bg.base,
      "textLink.activeForeground": palette.accent.primary,
      "textLink.foreground": palette.accent.primary,
      "textPreformat.foreground": palette.state.warning,
      "textSeparator.foreground": palette.bg.base,

      // ----------------------------------------------------------------------
      // TITLE BAR
      // ----------------------------------------------------------------------
      "titleBar.activeBackground": palette.bg.base,
      "titleBar.activeForeground": palette.accent.primary,
      "titleBar.inactiveBackground": palette.bg.base,
      "titleBar.inactiveForeground": alpha(palette.fg.bright, 0.6),

      // ----------------------------------------------------------------------
      // TREE
      // ----------------------------------------------------------------------
      "tree.indentGuidesStroke": palette.fg.dimmed,

      // ----------------------------------------------------------------------
      // WALKTHROUGH
      // ----------------------------------------------------------------------
      "walkThrough.embeddedEditorBackground": palette.bg.base,
    },

    // ========================================================================
    // SEMANTIC TOKEN COLORS
    // ========================================================================
    semanticTokenColors: {
      "*.abstract": { fontStyle: "italic" },
      "*.async": {},
      "*.callable": {},
      "*.consuming": {},
      "*.controlFlow": {},
      "*.crateRoot": { fontStyle: "bold" },
      "*.declaration": {},
      "*.defaultLibrary": {},
      "*.definition": {},
      "*.deprecated": { fontStyle: "strikethrough" },
      "*.documentation": { fontStyle: "italic" },
      "*.injected": {},
      "*.intraDocLink": { fontStyle: "underline" },
      "*.library": {},
      "*.modification": {},
      "*.mutable": { fontStyle: "underline" },
      "*.public": {},
      "*.readonly": {},
      "*.reference": {},
      "*.static": {},
      "*.trait": {},
      "*.unsafe": { foreground: palette.syntax.storage },
      "angle": palette.accent.pink,
      "arithmetic": { foreground: palette.syntax.keyword, fontStyle: "bold" },
      "attribute": palette.syntax.attribute,
      "attributeBracket": palette.syntax.keyword,
      "bitwise": { foreground: palette.syntax.keyword, fontStyle: "bold" },
      "boolean": palette.syntax.number,
      "brace": palette.syntax.storage,
      "bracket": palette.syntax.storage,
      "builtinAttribute": palette.syntax.attribute,
      "builtinType": palette.syntax.builtin,
      "character": palette.syntax.string,
      "class": { foreground: palette.syntax.type, fontStyle: "bold" },
      "colon": palette.syntax.punctuation,
      "comma": palette.syntax.punctuation,
      "comment": { foreground: palette.syntax.comment, fontStyle: "italic" },
      "comparison": { foreground: palette.syntax.keyword, fontStyle: "bold" },
      "const": palette.syntax.constant,
      "constParameter": palette.syntax.constant,
      "decorator": palette.syntax.function,
      "derive": palette.syntax.attribute,
      "deriveHelper": palette.syntax.attribute,
      "dot": { foreground: palette.syntax.keyword, fontStyle: "bold" },
      "enum": { foreground: palette.syntax.type, fontStyle: "bold" },
      "enumMember": palette.syntax.constant,
      "escapeSequence": { foreground: palette.syntax.escape, fontStyle: "bold" },
      "event": palette.syntax.constant,
      "formatSpecifier": palette.syntax.constant,
      "function": palette.syntax.function,
      "interface": { foreground: palette.syntax.type, fontStyle: "bold" },
      "invalidEscapeSequence": palette.syntax.error,
      "keyword": { foreground: palette.syntax.keyword, fontStyle: "bold" },
      "label": palette.syntax.storage,
      "lifetime": palette.syntax.builtin,
      "logical": { foreground: palette.syntax.keyword, fontStyle: "bold" },
      "macro": palette.syntax.storage,
      "macroBang": palette.syntax.storage,
      "method": palette.syntax.function,
      "namespace": palette.syntax.namespace,
      "number": palette.syntax.number,
      "operator": { foreground: palette.syntax.keyword, fontStyle: "bold" },
      "parameter": { foreground: palette.syntax.type, fontStyle: "bold" },
      "parenthesis": palette.syntax.storage,
      "procMacro": palette.syntax.storage,
      "property": palette.syntax.property,
      "punctuation": palette.syntax.punctuation,
      "regexp": palette.syntax.string,
      "selfKeyword": { foreground: palette.syntax.keyword, fontStyle: "bold" },
      "selfTypeKeyword": { foreground: palette.syntax.type, fontStyle: "bold" },
      "semicolon": palette.syntax.storage,
      "static": palette.syntax.constant,
      "string": palette.syntax.string,
      "struct": { foreground: palette.syntax.type, fontStyle: "bold" },
      "toolModule": palette.syntax.attribute,
      "type": { foreground: palette.syntax.type, fontStyle: "bold" },
      "typeAlias": { foreground: palette.syntax.type, fontStyle: "bold" },
      "typeParameter": { foreground: palette.syntax.type, fontStyle: "bold" },
      "union": { foreground: palette.syntax.type, fontStyle: "bold" },
      "unresolvedReference": palette.syntax.error,
      "variable": palette.syntax.type,
    },

    // ========================================================================
    // TOKEN COLORS (TextMate Syntax Highlighting)
    // All language scopes preserved
    // ========================================================================
    tokenColors: [
      // Italic styles for various constructs
      {
        scope: [
          "abstract.definition.fsharp entity",
          "abstract.definition.fsharp keyword",
          "comment",
          "comment.block.documentation storage.type.class",
          "comment.block.documentation.phpdoc.php keyword",
          "comment.block.documentation.rust",
          "comment.block.documentation.scala keyword",
          "comment.block.documentation.scala variable.parameter",
          "comment.block.javadoc.java keyword",
          "comment.block.javadoc.java variable.parameter.java",
          "comment.block.lua",
          "comment.block.rust",
          "comment.line.documentation.rust",
          "comment.line.double-dash.documentation.lua",
          "comment.line.double-slash.rust",
          "comment.line.roxygen.r keyword",
          "comment.line.roxygen.r variable.parameter.r",
          "constant.other.math",
          "constant.other.placeholder",
          "constant.other.symbol.hashkey.ruby",
          "constant.other.symbol.hashkey.ruby punctuation.definition.constant.ruby",
          "constant.other.symbol.ruby",
          "constant.other.table-name",
          "entity.alias.import.go",
          "entity.name.footnote",
          "entity.name.function.directive.graphql",
          "entity.name.record.field.accessor.elm",
          "entity.name.scope-resolution.function.call",
          "entity.name.type.kotlin",
          "entity.other",
          "function.anonymous keyword",
          "keyword.control.clojure",
          "keyword.control.export",
          "keyword.control.inheritance.coffee",
          "keyword.declaration.enum.rust",
          "keyword.declaration.struct.rust",
          "keyword.declaration.trait.rust",
          "keyword.declaration.type.rust",
          "keyword.function.go",
          "keyword.import",
          "keyword.language.gherkin.feature.step",
          "keyword.operator.documentation.powershell",
          "keyword.other.array.phpdoc.php",
          "keyword.other.base.cs",
          "keyword.other.capture-specifier",
          "keyword.other.import",
          "keyword.other.this.cs",
          "keyword.package",
          "keyword.type.cs",
          "markup.italic",
          "markup.quote",
          "meta.import keyword.control",
          "meta.preprocessor.pragma.nim",
          "punctuation.definition.comment",
          "sharing.modifier",
          "source.apex keyword.type",
          "source.clojure meta.symbol.dynamic",
          "source.go storage.type",
          "source.graphql support.type.enum",
          "source.hlsl storage.type.basic",
          "source.nim storage.type.concrete",
          "source.ocaml entity.name.filename",
          "source.python support.type.python",
          "source.r meta.function.r keyword.control.r",
          "source.reason entity.name.filename",
          "source.scala entity.name.class",
          "source.swift keyword.other.declaration-specifier",
          "source.swift support.type",
          "source.tf meta.keyword.number",
          "source.tf meta.keyword.string",
          "source.vala storage.type.generic",
          "source.wsd keyword.control.diagram",
          "storage.modifier",
          "storage.modifier.mut.rust",
          "storage.modifier.rust",
          "storage.type.built-in",
          "storage.type.core.rust",
          "storage.type.function.kotlin",
          "storage.type.integral",
          "storage.type.modifier",
          "storage.type.php",
          "storage.type.primitive",
          "storage.type.scala",
          "support.class.builtin",
          "support.constant.vendored",
          "support.function.builtin.go",
          "support.function.textit",
          "support.type.builtin",
          "support.type.core.rust",
          "support.type.julia",
          "support.type.primitive",
          "support.type.vendored",
          "support.variable.swift",
          "tag.decorator.js entity.name.tag.js",
          "tag.decorator.js punctuation.definition.tag.js",
          "text.tex support.function.emph",
          "variable.language",
          "variable.other.field",
          "variable.other.member",
          "variable.other.member.c",
          "variable.other.object.property",
          "variable.other.property",
          "variable.other.table.property.lua",
          "variable.parameter.function.language.special",
        ],
        settings: { fontStyle: "italic" },
      },

      // Storage types, tags - Orange
      {
        scope: [
          "binding.fsharp keyword",
          "comment.block.documentation punctuation.definition.block.tag",
          "comment.block.documentation punctuation.definition.inline.tag",
          "constant.language.empty-list.haskell",
          "entity.name.function.macro.rules.rust",
          "entity.name.function.macro.rust",
          "entity.name.tag",
          "entity.name.type.macro.rust",
          "entity.tag.apacheconf",
          "function.anonymous keyword",
          "function.anonymous keyword.symbol.fsharp",
          "keyword.control.class",
          "keyword.control.clojure",
          "keyword.control.def",
          "keyword.control.fun",
          "keyword.control.function-end.lua",
          "keyword.control.goto.lua",
          "keyword.declaration.dart",
          "keyword.function.go",
          "keyword.local.lua",
          "keyword.operator.macro.dollar.rust",
          "keyword.other.base.cs",
          "keyword.other.declaration-specifier.swift",
          "keyword.other.fn.rust",
          "keyword.other.julia",
          "keyword.other.nim",
          "keyword.other.rust",
          "keyword.other.skinparam.keyword",
          "keyword.other.this.cs",
          "keyword.other.var.cs",
          "markup.bold",
          "markup.deleted.diff",
          "markup.italic",
          "meta.brace.round.ts",
          "meta.class.identifier storage.modifier",
          "meta.embedded.block variable.language punctuation.definition.variable.php",
          "meta.function.powershell storage.type.powershell",
          "meta.macro.rust",
          "meta.separator",
          "punctuation.definition.bold",
          "punctuation.definition.italic",
          "punctuation.definition.ng-binding-name.begin.html",
          "punctuation.definition.ng-binding-name.end.html",
          "punctuation.definition.parameters.begin.ts",
          "punctuation.definition.parameters.end.ts",
          "punctuation.definition.string",
          "punctuation.section.parameters.begin.bracket.round.cpp",
          "punctuation.section.parameters.end.bracket.round.cpp",
          "punctuation.section.parens.begin.bracket.round.cpp",
          "punctuation.section.parens.end.bracket.round.cpp",
          "punctuation.terminator.function",
          "source.go keyword",
          "source.julia storage.modifier",
          "source.ocaml keyword markup.underline",
          "source.ocaml storage.type markup.underline",
          "source.r meta.function.r keyword.control.r",
          "source.scala keyword.declaration",
          "source.tf support.class.variable",
          "source.wsd keyword.other.class",
          "source.wsd keyword.other.linebegin",
          "storage.modifier.static.rust",
          "storage.modifier.super",
          "storage.type",
          "storage.type.alias.go",
          "storage.type.const.go",
          "storage.type.def",
          "storage.type.func.go",
          "storage.type.interface.go",
          "storage.type.type.go",
          "storage.type.var.go",
          "support.type.exception.python",
          "variable.language",
          "variable.language punctuation.definition.variable",
          "variable.parameter.function.language.special",
        ],
        settings: { foreground: palette.syntax.storage },
      },

      // Italic storage types
      {
        scope: [
          "binding.fsharp keyword",
          "binding.fsharp keyword.symbol",
          "entity.name.function.swift",
          "entity.name.section.fsharp",
          "entity.name.section.fsharp keyword",
          "entity.name.section.latex",
          "keyword.begin.tag.ejs",
          "keyword.control.class",
          "keyword.control.cucumber.table",
          "keyword.control.def",
          "keyword.control.default",
          "keyword.control.directive",
          "keyword.control.function-end.lua",
          "keyword.declaration.dart",
          "keyword.format.specifier.fsharp",
          "keyword.language.gherkin.feature.scenario",
          "keyword.operator.function.infix",
          "keyword.operator.other.powershell",
          "keyword.other.declaration-specifier.swift",
          "keyword.other.julia",
          "keyword.other.nim",
          "keyword.other.rust",
          "keyword.other.skinparam",
          "keyword.other.unit",
          "keyword.other.using.vala",
          "keyword.other.var.cs",
          "keyword.symbol.fsharp",
          "meta.class.identifier storage.modifier",
          "meta.import.haskell keyword",
          "namespace.open.fsharp entity",
          "namespace.open.fsharp keyword",
          "punctuation.definition.variable",
          "record.fsharp keyword",
          "source.apacheconf keyword",
          "source.c keyword.other",
          "source.cpp keyword.other",
          "source.cs keyword.other",
          "source.css keyword.control",
          "source.css keyword.operator",
          "source.css variable.parameter",
          "source.go keyword",
          "source.lua storage.type.function",
          "string.tag.lua",
          "source.nim keyword.other",
          "source.nim keyword.other.common.function",
          "source.objc keyword.other.property.attribute",
          "source.ocaml constant.language constant.numeric entity.other.attribute-name.id.css",
          "source.ocaml keyword markup.underline",
          "source.python meta.function.decorator.python support.type.python",
          "source.reason entity.other.attribute-name constant.language constant.numeric",
          "source.scala entity.name.class.declaration",
          "source.scala keyword.declaration",
          "source.sql keyword.other",
          "source.toml entity.other.attribute-name",
          "source.toml keyword",
          "source.wsd keyword.other",
          "storage.modifier.array.bracket",
          "storage.modifier.import",
          "storage.modifier.package",
          "storage.modifier.static.rust",
          "storage.modifier.using.vala",
          "storage.type",
          "string.interpolated variable.parameter",
          "variable.parameter.handlebars",
          "variable.parameter.r",
        ],
        settings: { fontStyle: "italic" },
      },

      // Punctuation - Muted foreground
      {
        scope: [
          "binding.fsharp keyword.symbol.fsharp",
          "constant.character",
          "constant.escape",
          "constant.name.attribute.tag.pug",
          "constant.other.description.jsdoc",
          "entity.name.footnote",
          "entity.name.record.field.accessor.elm",
          "entity.name.record.field.elm",
          "entity.other.attribute-name strong",
          "keyword.begin.tag.ejs",
          "keyword.operator.other.powershell",
          "keyword.other.array.phpdoc.php",
          "markup meta punctuation.definition",
          "meta.array.julia",
          "meta.attribute-selector punctuation.definition.entity",
          "meta.bracket.julia",
          "meta.link.inline punctuation.definition.string",
          "punctuation.definition.list_item",
          "punctuation.definition.parameters.begin.lua",
          "punctuation.definition.parameters.finish.lua",
          "punctuation.separator.arguments.lua",
          "punctuation.separator.key-value",
          "source meta.brace",
          "source punctuation",
          "source.clojure meta.symbol",
          "source.css entity.other",
          "source.ocaml entity.name.filename",
          "source.ocaml punctuation.definition.tag",
          "source.reason entity.name.filename",
          "source.sql",
          "storage.modifier.array.bracket",
          "text.html punctuation",
          "text.html.markdown",
        ],
        settings: { foreground: palette.syntax.punctuation },
      },

      // Comments
      {
        scope: [
          "comment",
          "comment.block.documentation punctuation.definition.bracket",
          "comment.line.double-dash.lua",
          "comment.line.shebang.lua",
          "punctuation.definition.comment",
          "punctuation.definition.comment.lua",
          "punctuation.definition.tag",
          "source.ocaml comment constant.regexp meta.separator",
        ],
        settings: { foreground: palette.syntax.comment },
      },

      // Built-in types - Lime/Yellow-green
      {
        scope: [
          "comment.block.documentation entity.name.type",
          "comment.block.documentation.phpdoc.php keyword.other.type.php",
          "constant.other.reference",
          "constant.other.symbol.hashkey.ruby",
          "constant.other.symbol.hashkey.ruby punctuation.definition.constant.ruby",
          "entity.name.lifetime.rust",
          "entity.name.type.annotation.kotlin",
          "entity.name.type.declaration.rust",
          "entity.name.type.enum.rust",
          "entity.name.type.fsharp",
          "entity.name.type.kotlin",
          "entity.name.type.lifetime.rust",
          "entity.name.type.metavariable.rust",
          "entity.name.type.numeric.rust",
          "entity.name.type.option.rust",
          "entity.name.type.primitive.rust",
          "entity.name.type.result.rust",
          "entity.name.type.rust",
          "entity.name.type.struct.rust",
          "entity.name.type.trait.rust",
          "entity.other.attribute-name.id",
          "entity.other.attribute-name.id punctuation.definition.entity",
          "keyword.type",
          "markup punctuation.definition",
          "meta.type.annotation entity.name.type",
          "meta.type.parameters entity.name.type",
          "punctuation.definition.lifetime.rust",
          "punctuation.definition.storage.type.objc",
          "punctuation.definition.string.begin.html",
          "punctuation.definition.string.end.html",
          "punctuation.definition.typeparameters",
          "punctuation.separator.clause-head-body",
          "source.apex storage.type",
          "source.cpp entity.name.type",
          "source.cpp storage.type.cpp",
          "source.elm storage.type",
          "source.go storage.type",
          "source.graphql support.type",
          "source.groovy storage.type",
          "source.haskell storage.type",
          "source.hlsl storage.type.basic",
          "source.hlsl support.type.other",
          "source.java storage.type",
          "source.nim storage.type",
          "source.python support.type.python",
          "source.reason support.type string",
          "source.scala entity.name.class",
          "source.swift support.type",
          "source.tf meta.keyword.number",
          "source.tf meta.keyword.string",
          "source.vala storage.type",
          "storage.class.std.rust",
          "storage.modifier.lifetime.rust",
          "storage.type.attribute.lua",
          "storage.type.built-in",
          "storage.type.c",
          "storage.type.core.rust",
          "storage.type.cs",
          "storage.type.generic.lua",
          "storage.type.integral",
          "storage.type.objc",
          "storage.type.php",
          "storage.type.powershell",
          "storage.type.primitive",
          "storage.type.r",
          "storage.type.user-defined",
          "string.other.link.title.markdown",
          "support.class.builtin",
          "support.class.crystal",
          "support.type.builtin",
          "support.type.julia",
          "support.type.lua",
          "support.type.primitive",
          "support.type.primitive.ts",
          "support.type.vb",
          "support.variable.property",
        ],
        settings: { foreground: palette.syntax.builtin },
      },

      // Constants - Pink
      {
        scope: [
          "constant",
          "constant.character.entity",
          "constant.character.format.placeholder",
          "constant.character.math",
          "constant.other.placeholder",
          "entity.helper.apacheconf",
          "entity.name.function.preprocessor.c",
          "entity.name.tag.html",
          "entity.name.type.type-parameter.cs",
          "entity.other.attribute-name.class",
          "markup.quote",
          "meta.attribute.id entity.other.attribute-name",
          "meta.table.lua variable.other",
          "meta.tag.attributes entity.other.attribute-name",
          "punctuation.bracket.angle",
          "punctuation.definition.constant",
          "punctuation.definition.entity",
          "source.cpp variable.other.enummember",
          "source.cs entity.other.attribute-name",
          "source.graphql constant.character",
          "source.reason constant.language.list",
          "storage.type.module.go",
          "storage.type.scala",
          "support.class.math",
          "support.constant",
          "support.constant punctuation.definition.variable",
          "support.variable.class.hideshow",
          "support.variable.magic",
          "text.html entity.other.attribute-name",
          "text.xml entity.other.attribute-name",
          "variable.language.crystal",
          "variable.other.constant",
        ],
        settings: { foreground: palette.syntax.constant },
      },

      // Types/Classes - Cyan bold
      {
        scope: [
          "constant.character.escape",
          "constant.character.escape punctuation.definition.keyword",
          "constant.other.haskell",
          "entity.global.clojure",
          "entity.name.class.lua",
          "entity.name.function-table.lua",
          "entity.name.type",
          "entity.name.type.class",
          "entity.namespace.r",
          "entity.other.inherited-class.python",
          "keyword.format.specifier.fsharp",
          "meta.embedded.block.php punctuation.definition.variable.php",
          "meta.embedded.line.crystal punctuation.section.embedded",
          "meta.embedded.line.crystal punctuation.section.embedded source.crystal",
          "meta.method-call.groovy storage.type.groovy",
          "punctuation.definition.interpolation",
          "punctuation.definition.template-expression",
          "punctuation.section.embedded",
          "punctuation.section.embedded source.swift",
          "punctuation.section.embedded.begin.ruby",
          "punctuation.section.embedded.end.ruby source.ruby",
          "punctuation.section.tag",
          "source.clojure punctuation.section.metadata",
          "source.clojure punctuation.section.set",
          "source.js constant.other.object.key.js string.unquoted.label.js",
          "source.js punctuation.section.embedded",
          "source.objc entity.name.tag",
          "source.ocaml entity.name.class constant.numeric",
          "source.python meta.function-call.python support.type.python",
          "source.reason entity.name.class",
          "source.scala entity.name.class.declaration",
          "source.tf meta.keyword.list",
          "source.tf meta.keyword.map",
          "source.vala storage.type",
          "storage.modifier.using.vala",
          "storage.type.string.python",
          "string.interpolated.dollar punctuation.definition.string",
          "string.interpolated.pug",
          "string.quoted.other.literal.upper.crystal punctuation.definition.string",
          "string.replacement.apacheconf",
          "support.class",
          "support.class.lua",
          "support.constant.handlebars",
          "support.constant.math",
          "support.function.macro.julia",
          "support.module.elm",
          "support.variable.class.group",
          "support.variable.lua",
          "variable.other.bracket punctuation.definition.variable",
        ],
        settings: { foreground: palette.syntax.type, fontStyle: "bold" },
      },

      // Escape sequences - Cyan bold
      {
        scope: [
          "constant.character.escape.backslash.rust",
          "constant.character.escape.bit.rust",
          "constant.character.escape.byte.lua",
          "constant.character.escape.lua",
          "constant.character.escape.rust",
          "constant.character.escape.unicode.lua",
          "constant.character.escape.unicode.punctuation.rust",
          "constant.character.escape.unicode.rust",
        ],
        settings: { foreground: palette.syntax.escape, fontStyle: "bold" },
      },

      // Strings - Yellow
      {
        scope: [
          "constant.character.literal.scala",
          "constant.language.boolean.false.ts",
          "constant.language.boolean.true.ts",
          "constant.language.dart",
          "constant.numeric.dart",
          "constant.numeric.decimal.cpp",
          "constant.numeric.decimal.ts",
          "entity.name.import.go",
          "entity.name.type.module.go",
          "markup.inline.raw punctuation.definition.raw",
          "markup.inline.raw.string",
          "markup.inserted.diff",
          "markup.raw.texttt",
          "punctuation.definition.string.begin.lua",
          "punctuation.definition.string.begin.ts",
          "punctuation.definition.string.end.lua",
          "punctuation.definition.string.end.ts",
          "punctuation.definition.string.template",
          "source.css support.constant",
          "source.scala punctuation.definition.character",
          "source.tf entity.name",
          "string",
          "string.interpolated.python string.quoted.single.python",
          "string.quoted.double.heredoc",
          "string.quoted.double.interpolated.crystal",
          "string.quoted.double.interpolated.crystal punctuation.definition.string",
          "string.quoted.double.lua",
          "string.quoted.interpolated.vala",
          "string.quoted.interpolated.vala punctuation.definition.string",
          "string.quoted.other.multiline.lua",
          "string.quoted.single.lua",
          "string.regexp.apacheconf",
          "string.template",
          "text.html.derivative",
          "text.tex markup.raw",
          "variable.other.constant.ts",
        ],
        settings: { foreground: palette.syntax.string },
      },

      // Numbers/Constants - Purple
      {
        scope: [
          "constant.integer.apacheconf",
          "constant.language",
          "constant.language.lua",
          "constant.language punctuation.definition.variable",
          "constant.numeric",
          "constant.numeric.float.hexadecimal.lua",
          "constant.numeric.float.lua",
          "constant.numeric.integer.hexadecimal.lua",
          "constant.numeric.integer.lua",
          "constant.others.fsharp",
          "keyword.operator.null-conditional.cs",
          "keyword.operator.nullable-type",
          "keyword.other.unit",
          "markup.inline.raw.string.markdown",
          "punctuation.separator.decimal.period.php",
          "punctuation.separator.question-mark.cs",
          "source.toml constant",
          "string.quoted.double.skinparam.value",
        ],
        settings: { foreground: palette.syntax.number },
      },

      // Rust numbers - Purple
      {
        scope: [
          "constant.language.bool.rust",
          "constant.numeric.bin.rust",
          "constant.numeric.decimal.exponent.mantissa.rust",
          "constant.numeric.decimal.rust",
          "constant.numeric.hex.rust",
          "constant.numeric.oct.rust",
          "constant.other.caps.rust",
          "punctuation.separator.dot.decimal.rust",
        ],
        settings: { foreground: palette.syntax.number },
      },

      // Namespaces/Support - Light blue
      {
        scope: [
          "constant.language.unit.fsharp",
          "entity.mime-type.apacheconf",
          "entity.name",
          "entity.name.function.call.kotlin",
          "entity.name.function.infix",
          "entity.name.module.rust",
          "entity.name.namespace.rust",
          "entity.name.scope-resolution.function.call",
          "entity.name.type.namespace",
          "entity.other",
          "entity.other.attribute-name.html",
          "entity.other.ng-binding-name.template.html",
          "keyword.language.gherkin.feature.scenario",
          "keyword.operator.function.infix",
          "markup.changed.git_gutter",
          "markup.underline",
          "meta.import.rust",
          "meta.symbol.namespace.clojure",
          "meta.use.php",
          "meta.use.rust",
          "punctuation.definition.parameters",
          "source.nim keyword.other.common.function",
          "source.ocaml constant.language constant.numeric entity.other.attribute-name.id.css",
          "source.reason constant.language.unit",
          "source.reason entity.other.attribute-name constant.language constant.numeric",
          "source.wsd support.class.preprocessings",
          "support.class",
          "support.function",
          "support.function.construct",
          "support.orther.namespace.use.php",
          "support.other.namespace.php",
          "support.type",
          "text.tex support.function.texttt",
          "text.tex support.function.verb",
        ],
        settings: { foreground: palette.syntax.namespace },
      },

      // Keywords - Magenta
      {
        scope: [
          "constant.other.color",
          "constant.string.documentation.powershell",
          "entity.name.section",
          "entity.other.attribute-name.pseudo-class",
          "entity.other.attribute-name.pseudo-class.css punctuation.definition.entity.css",
          "entity.other.attribute-name.pseudo-element",
          "entity.other.attribute-name.pseudo-element.css punctuation.definition.entity.css",
          "keyword",
          "keyword.control",
          "keyword.control.lua",
          "keyword.control punctuation.definition.function",
          "keyword.control.class.ruby",
          "keyword.control.def.ruby",
          "keyword.import",
          "keyword.operator.lua",
          "keyword.other.class.fileds",
          "keyword.other.substitution",
          "keyword.other.template",
          "keyword.package",
          "markup.heading",
          "markup.heading punctuation.definition",
          "meta.expression.clojure",
          "meta.tag.sgml",
          "punctuation.accessor",
          "punctuation.definition.attribute",
          "punctuation.definition.directive",
          "punctuation.definition.keyword",
          "punctuation.definition.parameters.varargs",
          "punctuation.definition.preprocessor",
          "punctuation.section.directive",
          "punctuation.separator.hash.cs",
          "punctuation.separator.method",
          "punctuation.separator.namespace",
          "punctuation.separator.other.ruby",
          "punctuation.separator.pointer-access",
          "punctuation.separator.question-mark.cs",
          "punctuation.separator.slice.python",
          "sharing.modifier",
          "source.clojure storage.control",
          "source.go keyword.operator",
          "source.kotlin storage.type.import",
          "source.kotlin storage.type.package",
          "source.ocaml variable.interpolation string",
          "source.reason variable.interpolation",
          "source.toml entity.other.attribute-name",
          "storage.modifier",
          "storage.type.function.pug",
          "storage.type.modifier",
          "storage.type.rust",
          "tag.decorator.js entity.name.tag.js",
          "tag.decorator.js punctuation.definition.tag.js",
          "text.pug meta.tag.other",
          "text.pug storage.type",
          "variable.parameter.rest.lua",
        ],
        settings: { foreground: palette.syntax.keyword },
      },

      // Bold keywords/operators
      {
        scope: [
          "constant.other.color",
          "constant.other.symbol.hashkey.ruby punctuation.definition.constant.ruby",
          "constant.other.symbol.ruby punctuation.definition.constant.ruby",
          "constant.other.symbol.ruby punctuation.definition.constant.ruby",
          "entity.name.function.definition.special.constructor",
          "entity.name.function.definition.special.member.destructor.",
          "entity.name.section",
          "entity.name.type.annotation.kotlin",
          "entity.name.variable.parameter",
          "keyword",
          "keyword.control",
          "keyword.control.class.ruby",
          "keyword.control.def.ruby",
          "keyword.operator",
          "keyword.other.new",
          "keyword.other.substitution",
          "keyword.other.template",
          "markdown.heading",
          "markup punctuation.definition",
          "markup.bold",
          "markup.bold string",
          "markup.heading",
          "markup.inline.raw punctuation.definition.raw",
          "meta.function.parameters variable punctuation.definition.variable.php",
          "meta.function.parameters variable.other",
          "parameter.variable.function",
          "punctuation.accessor",
          "punctuation.bracket.angle",
          "punctuation.definition.preprocessor",
          "punctuation.section.directive",
          "punctuation.separator.hash.cs",
          "punctuation.separator.method",
          "punctuation.separator.namespace",
          "punctuation.separator.question-mark.cs",
          "source.go keyword.operator",
          "source.graphql support.type.builtin",
          "source.ocaml variable.interpolation string",
          "source.ruby punctuation.definition.variable",
          "source.wsd keyword.other.activity",
          "storage.type.annotation",
          "storage.type.function.arrow",
          "storage.type.function.coffee",
          "storage.type.function.pug",
          "storage.type.function.python",
          "storage.type.generic.wildcard",
          "storage.type.objc",
          "support.function.builtin.rust",
          "support.function.textbf",
          "variable.parameter",
          "variable.parameter.function.lua",
        ],
        settings: { fontStyle: "bold" },
      },

      // Placeholder - Yellow
      {
        scope: ["constant.other.placeholder"],
        settings: { foreground: palette.syntax.string },
      },

      // Functions - Green
      {
        scope: [
          "entity.name.function",
          "entity.name.function.lua",
          "entity.name.function.rust",
          "entity.name.section.fsharp entity.name.section.fsharp",
          "keyword.control.cucumber.table",
          "markup.link",
          "markup.underline.link",
          "markup.underline.link.image",
          "meta.class.body.groovy meta.method.body.java storage.type.groovy",
          "meta.function-call.generic.python",
          "meta.function.call.rust",
          "meta.function.definition.rust",
          "meta.method-call.groovy meta.method.groovy",
          "punctuation.decorator",
          "punctuation.definition.decorator",
          "source.tf support.class",
          "string.other.link",
          "support.function.any-method",
          "support.function.any-method.lua",
          "support.function.go",
          "support.function.library.lua",
          "support.function.lua",
          "support.other.variable",
          "support.type.property-name",
          "support.type.vendored",
          "support.variable.class.function",
          "text.tex punctuation.definition.function",
          "text.tex support.function",
          "variable.function",
        ],
        settings: { foreground: palette.syntax.function },
      },

      // Bold italic
      {
        scope: [
          "entity.name.lifetime.rust",
          "keyword.other.fn.rust",
          "markup.bold markup.italic",
          "markup.bold markup.italic string",
          "markup.italic markup.bold",
          "markup.italic markup.bold string",
          "markup.quote markup.bold",
          "markup.quote markup.bold string",
          "meta.attribute.id entity.other.attribute-name",
          "source.ocaml punctuation.definition.tag emphasis",
          "source.rust meta.attribute.rust",
          "source.tf entity.name",
          "storage.modifier.lifetime.rust",
          "text.html punctuation.section.embedded",
          "variable.other.c",
        ],
        settings: { fontStyle: "bold italic" },
      },

      // Variables - Cyan
      {
        scope: [
          "entity.name.module",
          "entity.name.package.go",
          "entity.name.package.kotlin",
          "entity.name.variable",
          "markup.list",
          "meta.embedded.block variable punctuation.definition.variable.php",
          "meta.function-call.arguments.python",
          "meta.template.expression.kotlin",
          "meta.toc-list.id.html",
          "meta.var.clojure",
          "parameter.variable.function",
          "punctuation.definition.annotation",
          "punctuation.definition.placeholder",
          "punctuation.definition.variable",
          "source.apacheconf",
          "source.c",
          "source.coffee",
          "source.coffee.embedded.source",
          "source.cpp",
          "source.crystal",
          "source.css entity.name.tag.custom",
          "source.elixir.embedded.source",
          "source.elm meta.declaration.module",
          "source.elm meta.value",
          "source.go",
          "source.groovy.embedded.source",
          "source.java meta.class.body.java",
          "source.json meta.structure.dictionary.json support.type.property-name.json",
          "source.julia",
          "source.objc",
          "source.powershell",
          "source.python",
          "source.reason variable.language",
          "source.reason variable.language string.other.link",
          "source.ruby",
          "source.scala entity.name.import",
          "source.shell",
          "source.sql.embedded",
          "source.swift",
          "source.tf meta.template.expression",
          "source.toml keyword",
          "storage.modifier.import",
          "storage.modifier.package",
          "storage.type.annotation",
          "string.quoted.double.class.other",
          "string.quoted.double.kotlin entity.string.template.element.kotlin",
          "string.quoted.interpolated.vala constant.character.escape.vala",
          "support",
          "support.type.nim",
          "variable",
          "variable.import.parameter",
          "variable.object",
          "variable.other",
          "variable.other.class",
          "variable.other.constant.elixir",
          "variable.other.lua",
          "variable.other.normal punctuation.definition.variable.shell",
          "variable.parameter",
        ],
        settings: { foreground: palette.syntax.type },
      },

      // Invalid - Strikethrough
      {
        scope: [
          "invalid",
          "invalid.illegal",
          "invalid.illegal.character.escape.lua",
          "invalid.illegal.unrecognized-string-escape.zig",
        ],
        settings: { foreground: palette.syntax.invalid, fontStyle: "strikethrough" },
      },

      // ======================================================================
      // ZIG LANGUAGE SUPPORT
      // ======================================================================
      {
        scope: ["comment.line.documentation.zig", "comment.line.double-slash.zig"],
        settings: { foreground: palette.syntax.comment, fontStyle: "italic" },
      },
      {
        scope: ["keyword.todo.zig"],
        settings: { foreground: palette.state.warning, fontStyle: "bold" },
      },
      {
        scope: [
          "keyword.storage.zig",
          "keyword.structure.zig",
          "keyword.statement.zig",
          "keyword.control.flow.zig",
          "keyword.control.async.zig",
          "keyword.control.trycatch.zig",
          "keyword.control.conditional.zig",
          "keyword.control.repeat.zig",
          "keyword.default.zig",
        ],
        settings: { foreground: palette.syntax.keyword, fontStyle: "bold" },
      },
      {
        scope: ["keyword.constant.default.zig", "keyword.constant.bool.zig"],
        settings: { foreground: palette.syntax.constant },
      },
      {
        scope: ["keyword.type.zig", "keyword.type.integer.zig", "keyword.type.c.zig"],
        settings: { foreground: palette.syntax.builtin },
      },
      {
        scope: ["storage.type.function.zig"],
        settings: { foreground: palette.syntax.storage, fontStyle: "bold" },
      },
      {
        scope: ["entity.name.function.zig", "entity.name.function.string.zig"],
        settings: { foreground: palette.syntax.function },
      },
      {
        scope: ["entity.name.type.zig"],
        settings: { foreground: palette.syntax.type, fontStyle: "bold" },
      },
      {
        scope: ["variable.zig", "variable.string.zig"],
        settings: { foreground: palette.syntax.type },
      },
      {
        scope: ["support.function.builtin.zig"],
        settings: { foreground: palette.syntax.attribute, fontStyle: "bold" },
      },
      {
        scope: [
          "string.quoted.double.zig",
          "string.multiline.zig",
          "string.quoted.single.zig",
        ],
        settings: { foreground: palette.syntax.string },
      },
      {
        scope: ["constant.character.escape.zig"],
        settings: { foreground: palette.syntax.escape, fontStyle: "bold" },
      },
      {
        scope: [
          "constant.numeric.hexfloat.zig",
          "constant.numeric.float.zig",
          "constant.numeric.decimal.zig",
          "constant.numeric.hexadecimal.zig",
          "constant.numeric.octal.zig",
          "constant.numeric.binary.zig",
        ],
        settings: { foreground: palette.syntax.number },
      },
      {
        scope: ["constant.numeric.invalid.zig"],
        settings: { foreground: palette.syntax.invalid, fontStyle: "strikethrough" },
      },
      {
        scope: [
          "keyword.operator.c-pointer.zig",
          "keyword.operator.comparison.zig",
          "keyword.operator.arithmetic.zig",
          "keyword.operator.bitwise.zig",
          "keyword.operator.special.zig",
          "keyword.operator.assignment.zig",
          "keyword.operator.question.zig",
        ],
        settings: { foreground: palette.syntax.keyword, fontStyle: "bold" },
      },
      {
        scope: [
          "punctuation.accessor.zig",
          "punctuation.comma.zig",
          "punctuation.separator.key-value.zig",
          "punctuation.terminator.statement.zig",
        ],
        settings: { foreground: palette.syntax.punctuation },
      },

      // ======================================================================
      // RUST LANGUAGE SUPPORT
      // ======================================================================
      {
        scope: [
          "keyword.control.rust",
          "keyword.operator.access.dot.rust",
          "keyword.operator.arrow.fat.rust",
          "keyword.operator.arrow.skinny.rust",
          "keyword.operator.assignment.equal.rust",
          "keyword.operator.assignment.rust",
          "keyword.operator.borrow.and.rust",
          "keyword.operator.borrow.rust",
          "keyword.operator.comparison.rust",
          "keyword.operator.dereference.rust",
          "keyword.operator.exponent.rust",
          "keyword.operator.exponent.sign.rust",
          "keyword.operator.key-value.rust",
          "keyword.operator.logical.rust",
          "keyword.operator.math.rust",
          "keyword.operator.namespace.rust",
          "keyword.operator.question.rust",
          "keyword.operator.range.rust",
          "keyword.operator.subpattern.rust",
          "keyword.other.crate.rust",
        ],
        settings: { foreground: palette.syntax.keyword },
      },
      {
        scope: [
          "entity.name.variable.lua",
          "meta.attribute.rust",
          "punctuation.brackets.attribute.rust",
          "punctuation.definition.attribute.rust",
          "storage.type.annotation.lua",
        ],
        settings: { foreground: palette.syntax.attribute },
      },
      {
        scope: [
          "meta.interpolation.rust",
          "punctuation.brackets.angle.rust",
          "punctuation.brackets.curly.rust",
          "punctuation.brackets.round.rust",
          "punctuation.brackets.square.rust",
          "punctuation.comma.rust",
          "punctuation.definition.interpolation.rust",
          "punctuation.semi.rust",
        ],
        settings: { foreground: palette.syntax.punctuation },
      },
      {
        scope: [
          "punctuation.definition.char.rust",
          "punctuation.definition.string.raw.rust",
          "punctuation.definition.string.rust",
          "string.quoted.byte.raw.rust",
          "string.quoted.double.rust",
          "string.quoted.single.char.rust",
        ],
        settings: { foreground: palette.syntax.string },
      },

      // ======================================================================
      // LUA/TYPESCRIPT/OTHER LANGUAGE SUPPORT
      // ======================================================================
      {
        scope: [
          "entity.other.attribute.lua",
          "punctuation.definition.typeparameters.begin.ts",
          "punctuation.definition.typeparameters.end.ts",
          "variable.other.property",
        ],
        settings: { foreground: palette.syntax.property, fontStyle: "" },
      },
      {
        scope: [
          "source.dart",
          "source.go",
          "source.ts",
          "string.quoted.double.html",
          "variable.field.go",
        ],
        settings: { foreground: palette.fg.soft, fontStyle: "" },
      },
      {
        scope: ["support.class.console.ts", "support.function.console.ts"],
        settings: { foreground: palette.special.console, fontStyle: "bold underline" },
      },

      // ======================================================================
      // DEBUG TOKENS
      // ======================================================================
      {
        scope: ["token.debug-token"],
        settings: { foreground: palette.special.debugToken, fontStyle: "bold" },
      },
      {
        scope: ["token.error-token"],
        settings: { foreground: palette.special.errorToken },
      },
      {
        scope: ["token.info-token"],
        settings: { foreground: palette.special.infoToken },
      },
      {
        scope: ["token.warn-token"],
        settings: { foreground: palette.special.warnToken },
      },

      // ======================================================================
      // RUST/LUA VARIABLES
      // ======================================================================
      {
        scope: [
          "variable.language.self.lua",
          "variable.language.self.rust",
          "variable.language.super.rust",
          "variable.other.metavariable.name.rust",
          "variable.other.metavariable.specifier.rust",
          "variable.other.rust",
        ],
        settings: { foreground: palette.syntax.type },
      },
    ],
  };
};
